# Generated by Django 5.2.7 on 2025-12-13 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='teammembership',
            options={'ordering': ['joined_at'], 'verbose_name': 'Team Membership', 'verbose_name_plural': 'Team Memberships'},
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this team is active'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this membership is currently active'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, help_text='Team description and purpose'),
        ),
        migrations.AlterField(
            model_name='team',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Team lead/manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(help_text='Team members', related_name='teams', through='teams.TeamMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Team name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('LEAD', 'Team Lead'), ('SENIOR', 'Senior Member'), ('MEMBER', 'Member'), ('JUNIOR', 'Junior Member')], default='MEMBER', max_length=10),
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEAD', 'Team Lead'), ('SENIOR', 'Senior Member'), ('MEMBER', 'Member'), ('JUNIOR', 'Junior Member')], default='MEMBER', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Optional invitation message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_team_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Invitation',
                'verbose_name_plural': 'Team Invitations',
                'ordering': ['-created_at'],
                'unique_together': {('team', 'invited_user', 'status')},
            },
        ),
    ]
