# Generated by Django 5.2.7 on 2026-07-24 15:17

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_start_date_before_due_date_and_more'),
        ('teams', '0002_alter_team_options_alter_teammembership_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, help_text='Target metric value', max_digits=10, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current metric value', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meeting_type', models.CharField(choices=[('STANDUP', 'Daily Standup'), ('WEEKLY', 'Weekly Sync'), ('PLANNING', 'Sprint Planning'), ('RETRO', 'Retrospective'), ('1ON1', 'One-on-One'), ('ALL_HANDS', 'All Hands')], default='STANDUP', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('location', models.CharField(blank=True, help_text='Physical location or video call link', max_length=200)),
                ('agenda', models.TextField(blank=True, help_text='Meeting agenda')),
                ('notes', models.TextField(blank=True, help_text='Meeting notes')),
                ('action_items', models.JSONField(blank=True, default=list, help_text='Action items from meeting')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary team for the project')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_at'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='teammembership',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Team Membership', 'verbose_name_plural': 'Team Memberships'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lead',
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 24, 15, 17, 7, 731857, tzinfo=datetime.timezone.utc), help_text='When invitation expires'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammembership',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='contributions',
            field=models.TextField(blank=True, help_text='Notable contributions to the team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='performance_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Performance rating (0-5)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='receive_notifications',
            field=models.BooleanField(default=True, help_text='Receive team notifications'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='tasks_completed',
            field=models.IntegerField(default=0, help_text='Number of tasks completed as team member'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='teams.TeamMembership', through_fields=('team', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('CO_LEAD', 'Co-Lead'), ('LEAD', 'Lead')], default='MEMBER', max_length=10),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('CO_LEAD', 'Co-Lead'), ('LEAD', 'Lead')], default='MEMBER', max_length=10),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['invited_user', 'status'], name='teams_teami_invited_9c17c1_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['expires_at', 'status'], name='teams_teami_expires_bf9472_idx'),
        ),
        migrations.AddField(
            model_name='teamgoal',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_team_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamgoal',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='teams.team'),
        ),
        migrations.AddField(
            model_name='teammeeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='team_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammeeting',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammeeting',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='teams.team'),
        ),
        migrations.AddField(
            model_name='teamproject',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teams', to='projects.project'),
        ),
        migrations.AddField(
            model_name='teamproject',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_projects', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='teammeeting',
            index=models.Index(fields=['team', 'scheduled_at'], name='teams_teamm_team_id_1248a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamproject',
            unique_together={('team', 'project')},
        ),
    ]
