# Generated by Django 5.2.7 on 2026-08-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teamgoal_teammeeting_teamproject_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='allow_self_join',
            field=models.BooleanField(default=False, help_text='Whether users can join the team without an invitation'),
        ),
        migrations.AddField(
            model_name='team',
            name='completed_projects',
            field=models.PositiveIntegerField(default=0, help_text='Cached count of completed projects assigned to the team'),
        ),
        migrations.AddField(
            model_name='team',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of members (null = unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='total_projects',
            field=models.PositiveIntegerField(default=0, help_text='Cached count of projects assigned to the team'),
        ),
    ]
