# Generated by Django 5.2.7 on 2025-12-01 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('due_date__isnull', True), ('start_date__lte', models.F('due_date')), _connector='OR'), name='project_start_date_before_due_date'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='project_progress_percentage_valid'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('budget__isnull', True), ('budget__gte', 0), _connector='OR'), name='project_budget_positive'),
        ),
    ]
