# Generated by Django 5.2.7 on 2026-08-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_start_date_before_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
