# Generated by Django 5.2.7 on 2026-08-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_commentmention_mentioned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Whether this comment has been soft-deleted'),
        ),
    ]
