# Generated by Django 5.2.7 on 2026-08-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('LIKE', '👍'), ('LOVE', '❤️'), ('LAUGH', '😄'), ('CONFUSED', '😕'), ('CELEBRATE', '🎉'), ('HEART', '💓')], default='LIKE', max_length=10),
        ),
    ]
