# Generated by Django 5.2.7 on 2025-12-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_rate__isnull', True), ('hourly_rate__gte', 0), _connector='OR'), name='user_hourly_rate_positive'),
        ),
    ]
