# Generated by Django 5.2.7 on 2025-12-13 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has seen this activity')),
                ('is_important', models.BooleanField(default=False, help_text='Whether this is marked as important')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Activity Feed Item',
                'verbose_name_plural': 'Activity Feed Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('COMMENTED', 'Commented'), ('STATUS_CHANGED', 'Status Changed'), ('UPLOADED', 'Uploaded File'), ('DOWNLOADED', 'Downloaded File'), ('INVITED', 'Invited'), ('JOINED', 'Joined'), ('LEFT', 'Left'), ('ARCHIVED', 'Archived'), ('RESTORED', 'Restored')], help_text='Type of action performed', max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='changes',
            field=models.JSONField(blank=True, help_text='JSON containing before/after values of changes', null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='content_type',
            field=models.ForeignKey(help_text='Type of object affected', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(help_text='Human-readable description of the action'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='object_id',
            field=models.PositiveIntegerField(help_text='ID of object affected'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser/device user agent string'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='activity_ac_created_a8727e_idx'),
        ),
        migrations.AddField(
            model_name='activityfeed',
            name='activity',
            field=models.ForeignKey(help_text='The activity log entry', on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='activity.activitylog'),
        ),
        migrations.AddField(
            model_name='activityfeed',
            name='user',
            field=models.ForeignKey(help_text='User this feed item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activity_feed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['user', 'is_read'], name='activity_ac_user_id_8ddeb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activityfeed',
            unique_together={('user', 'activity')},
        ),
    ]
