# Generated by Django 5.2.7 on 2025-12-14 16:16

import django.core.validators
import django.db.models.deletion
import files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='filename',
        ),
        migrations.AddField(
            model_name='attachment',
            name='download_count',
            field=models.IntegerField(default=0, help_text='Number of times file has been downloaded'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_hash',
            field=models.CharField(db_index=True, default='', help_text='SHA256 hash of file content', max_length=64),
        ),
        migrations.AddField(
            model_name='attachment',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_safe',
            field=models.BooleanField(default=True, help_text='Whether file passed security scan'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_scanned',
            field=models.BooleanField(default=False, help_text='Whether file has been scanned for viruses'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, help_text='Last download timestamp', null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='original_filename',
            field=models.CharField(default='', help_text='Original filename from upload', max_length=255),
        ),
        migrations.AddField(
            model_name='attachment',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for image files', null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(help_text='Type of object this file is attached to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True, help_text='Optional file description'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(help_text='The uploaded file', upload_to=files.models.get_upload_path, validators=[files.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'zip', 'rar', '7z', 'gz', 'html', 'css', 'js', 'json', 'xml'])]),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.BigIntegerField(help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(help_text='MIME type of the file', max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.PositiveIntegerField(help_text='ID of object this file is attached to'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded this file', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_type', 'object_id'], name='files_attac_content_28f0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='files_attac_uploade_175d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['file_hash'], name='files_attac_file_ha_9add2a_idx'),
        ),
    ]
