# Generated by Django 5.2.7 on 2025-12-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_attachment_options_remove_attachment_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_hash',
            field=models.CharField(db_index=True, help_text='SHA256 hash of file content', max_length=64),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='original_filename',
            field=models.CharField(help_text='Original filename from upload', max_length=255),
        ),
    ]
