# Generated by Django 5.2.7 on 2026-08-25 15:41

import django.core.validators
import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_attachment_file_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(help_text='The uploaded file', upload_to=files.models.get_upload_path, validators=[files.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'rar', '7z', 'gz', 'css', 'json'])]),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='is_safe',
            field=models.BooleanField(default=False, help_text='Whether file passed security scan (defaults unsafe until scanned)'),
        ),
    ]
