# Generated by Django 5.2.7 on 2026-08-13 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MENTION', 'Mentioned'), ('COMMENT', 'New Comment'), ('ASSIGNMENT', 'Task Assigned'), ('PROJECT_INVITE', 'Project Invitation'), ('TASK_COMPLETED', 'Task Completed'), ('DEADLINE_REMINDER', 'Deadline Reminder'), ('PROJECT_UPDATE', 'Project Update')], max_length=20)),
                ('title_template', models.TextField()),
                ('message_template', models.TextField()),
                ('email_subject_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['notification_type'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MENTION', 'Mentioned'), ('COMMENT', 'New Comment'), ('ASSIGNMENT', 'Task Assigned'), ('PROJECT_INVITE', 'Project Invitation'), ('TASK_COMPLETED', 'Task Completed'), ('DEADLINE_REMINDER', 'Deadline Reminder'), ('PROJECT_UPDATE', 'Project Update')], max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MENTION', 'Mentioned'), ('COMMENT', 'New Comment'), ('ASSIGNMENT', 'Task Assigned'), ('PROJECT_INVITE', 'Project Invitation'), ('TASK_COMPLETED', 'Task Completed'), ('DEADLINE_REMINDER', 'Deadline Reminder'), ('PROJECT_UPDATE', 'Project Update')], max_length=20)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['notification_type'],
            },
        ),
    ]
